FROM bitnami/spark:3.5



# Passa temporaneamente a root per installare i pacchetti
USER root

# Installa le librerie Python necessarie
RUN pip install --no-cache-dir numpy pandas pyarrow minio

# Torna all'utente di default non-root per maggiore sicurezza
USER 1001

WORKDIR /app

# Copia l'INTERA cartella 'src' dalla radice del progetto
COPY ./src /app/src

# Imposta la PYTHONPATH CORRETTA per puntare alla cartella che contiene i nostri moduli
ENV PYTHONPATH=/app/src